Building DAG of jobs...
shared_storage_local_copies: True
remote_exec: False
Using shell: /usr/bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job       count
------  -------
all           1
fastqc        1
total         2

Resources before job selection: {'_cores': 24, '_nodes': 9223372036854775807}
Ready jobs (1)
Select jobs to execute...
Using greedy selector because only single job has to be scheduled.
Selected jobs (1)
Resources after job selection: {'_cores': 23, '_nodes': 9223372036854775806}
Execute 1 jobs...

[Mon Aug 12 11:34:53 2024]
localrule fastqc:
    input: /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R1.fastq, /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R2.fastq
    output: fastqc/Id1_AA_fastqc
    jobid: 1
    reason: Missing output files: fastqc/Id1_AA_fastqc
    wildcards: sample=Id1_AA
    resources: tmpdir=/tmp

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 48, in __rule_fastqc
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        fastqc /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R1.fastq /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R2.fastq --outdir fastqc/Id1_AA_fastqc' returned non-zero exit status 2.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 48, in __rule_fastqc
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        fastqc /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R1.fastq /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R2.fastq --outdir fastqc/Id1_AA_fastqc' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 24:
Command 'set -euo pipefail;  
        fastqc /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R1.fastq /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R2.fastq --outdir fastqc/Id1_AA_fastqc' returned non-zero exit status 2.

RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 24:
Command 'set -euo pipefail;  
        fastqc /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R1.fastq /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R2.fastq --outdir fastqc/Id1_AA_fastqc' returned non-zero exit status 2.
[Mon Aug 12 11:34:53 2024]
Error in rule fastqc:
    jobid: 1
    input: /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R1.fastq, /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R2.fastq
    output: fastqc/Id1_AA_fastqc
    conda-env: /home/lucianhu/rna_snakemake/test_ting/.snakemake/conda/05db0ab98062ab2d5aa58ba7efe64bb3_
    shell:
        
        fastqc /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R1.fastq /home/lucianhu/rna_snakemake/rnaseq-tutorial/reads/Id1_AA-rep1.R2.fastq --outdir fastqc/Id1_AA_fastqc
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-08-12T113453.807820.snakemake.log
unlocking
removing lock
removing lock
removed all locks
Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    dag_api.execute_workflow(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/api.py", line 594, in execute_workflow
    workflow.execute(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1286, in execute
    raise WorkflowError("At least one job did not complete successfully.")
snakemake_interface_common.exceptions.WorkflowError: At least one job did not complete successfully.

WorkflowError:
At least one job did not complete successfully.
