Building DAG of jobs...
Forcing incomplete files:
	results/align/bam_original/WT_REP2_control/WT_REP2_control.Aligned.out.bam
	results/align/bam_original/WT_REP2_control/WT_REP2_control.Aligned.toTranscriptome.out.bam
shared_storage_local_copies: True
remote_exec: False
Using shell: /usr/bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job                            count
---------------------------  -------
align_paired                       1
all                                1
picard_mark_duplicates             2
samtools_markdup_processing        6
samtools_process                   1
stringtie                          6
total                             17

Resources before job selection: {'_cores': 24, '_nodes': 9223372036854775807}
Ready jobs (10)
Select jobs to execute...
Selected jobs (4)
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775803}
Execute 4 jobs...

[Sun Aug 18 19:39:34 2024]
Job 35: RAP1_REP2_treatment: Running Stringtie to assemble and quantify transcripts
Reason: Missing output files: results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.transcripts.gtf


[Sun Aug 18 19:39:34 2024]
Job 36: RAP1_REP3_treatment: Running Stringtie to assemble and quantify transcripts
Reason: Missing output files: results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.transcripts.gtf


[Sun Aug 18 19:39:34 2024]
Job 34: RAP1_REP1_treatment: Running Stringtie to assemble and quantify transcripts
Reason: Missing output files: results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.transcripts.gtf


[Sun Aug 18 19:39:34 2024]
Job 31: WT_REP1_control: Running Stringtie to assemble and quantify transcripts
Reason: Missing output files: results/stringtie/WT_REP1_control/WT_REP1_control.transcripts.gtf

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 747, in __rule_stringtie
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP2_treatment.stringtie.log' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 747, in __rule_stringtie
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP1_treatment.stringtie.log' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 747, in __rule_stringtie
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/RAP1_REP3_treatment/RAP1_REP3_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP3_treatment.stringtie.log' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 747, in __rule_stringtie
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/WT_REP1_control/WT_REP1_control.transcripts.gtf                   -A results/stringtie/WT_REP1_control/WT_REP1_control.gene.abundance.txt                   -C results/stringtie/WT_REP1_control/WT_REP1_control.coverage.gtf                   -b results/stringtie/WT_REP1_control/WT_REP1_control.ballgown                   -p 6                   -v                   -e &> logs/stringtie/WT_REP1_control.stringtie.log' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 747, in __rule_stringtie
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP2_treatment.stringtie.log' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 379:
Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP2_treatment.stringtie.log' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 747, in __rule_stringtie
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP1_treatment.stringtie.log' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 379:
Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP1_treatment.stringtie.log' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 747, in __rule_stringtie
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/RAP1_REP3_treatment/RAP1_REP3_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP3_treatment.stringtie.log' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 379:
Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/RAP1_REP3_treatment/RAP1_REP3_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP3_treatment.stringtie.log' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 747, in __rule_stringtie
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/WT_REP1_control/WT_REP1_control.transcripts.gtf                   -A results/stringtie/WT_REP1_control/WT_REP1_control.gene.abundance.txt                   -C results/stringtie/WT_REP1_control/WT_REP1_control.coverage.gtf                   -b results/stringtie/WT_REP1_control/WT_REP1_control.ballgown                   -p 6                   -v                   -e &> logs/stringtie/WT_REP1_control.stringtie.log' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 379:
Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/WT_REP1_control/WT_REP1_control.transcripts.gtf                   -A results/stringtie/WT_REP1_control/WT_REP1_control.gene.abundance.txt                   -C results/stringtie/WT_REP1_control/WT_REP1_control.coverage.gtf                   -b results/stringtie/WT_REP1_control/WT_REP1_control.ballgown                   -p 6                   -v                   -e &> logs/stringtie/WT_REP1_control.stringtie.log' returned non-zero exit status 1.

RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 379:
Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP1_treatment.stringtie.log' returned non-zero exit status 1.
RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 379:
Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP2_treatment.stringtie.log' returned non-zero exit status 1.
RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 379:
Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/RAP1_REP3_treatment/RAP1_REP3_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP3_treatment.stringtie.log' returned non-zero exit status 1.
RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 379:
Command 'set -euo pipefail;  
        stringtie results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/WT_REP1_control/WT_REP1_control.transcripts.gtf                   -A results/stringtie/WT_REP1_control/WT_REP1_control.gene.abundance.txt                   -C results/stringtie/WT_REP1_control/WT_REP1_control.coverage.gtf                   -b results/stringtie/WT_REP1_control/WT_REP1_control.ballgown                   -p 6                   -v                   -e &> logs/stringtie/WT_REP1_control.stringtie.log' returned non-zero exit status 1.
[Sun Aug 18 19:39:34 2024]
[Sun Aug 18 19:39:34 2024]
Error in rule stringtie:
    jobid: 36
    input: results/align/bam_markup/RAP1_REP3_treatment/RAP1_REP3_treatment.markdup.sorted.bam, resources/annotation.gtf
    output: results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.transcripts.gtf, results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.gene.abundance.txt, results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.coverage.gtf, results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.ballgown
    log: logs/stringtie/RAP1_REP3_treatment.stringtie.log (check log file(s) for error details)
    conda-env: /home/lucianhu/rna_snakemake/test_ting/.snakemake/conda/c5aa9c6478b88eb8815e34b057a49de2_
    shell:
        
        stringtie results/align/bam_markup/RAP1_REP3_treatment/RAP1_REP3_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP3_treatment.stringtie.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Sun Aug 18 19:39:34 2024]
Error in rule stringtie:
    jobid: 31
    input: results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam, resources/annotation.gtf
    output: results/stringtie/WT_REP1_control/WT_REP1_control.transcripts.gtf, results/stringtie/WT_REP1_control/WT_REP1_control.gene.abundance.txt, results/stringtie/WT_REP1_control/WT_REP1_control.coverage.gtf, results/stringtie/WT_REP1_control/WT_REP1_control.ballgown
    log: logs/stringtie/WT_REP1_control.stringtie.log (check log file(s) for error details)
    conda-env: /home/lucianhu/rna_snakemake/test_ting/.snakemake/conda/c5aa9c6478b88eb8815e34b057a49de2_
    shell:
        
        stringtie results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/WT_REP1_control/WT_REP1_control.transcripts.gtf                   -A results/stringtie/WT_REP1_control/WT_REP1_control.gene.abundance.txt                   -C results/stringtie/WT_REP1_control/WT_REP1_control.coverage.gtf                   -b results/stringtie/WT_REP1_control/WT_REP1_control.ballgown                   -p 6                   -v                   -e &> logs/stringtie/WT_REP1_control.stringtie.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Error in rule stringtie:
    jobid: 34
    input: results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam, resources/annotation.gtf
    output: results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.transcripts.gtf, results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.gene.abundance.txt, results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.coverage.gtf, results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.ballgown
    log: logs/stringtie/RAP1_REP1_treatment.stringtie.log (check log file(s) for error details)
    conda-env: /home/lucianhu/rna_snakemake/test_ting/.snakemake/conda/c5aa9c6478b88eb8815e34b057a49de2_
    shell:
        
        stringtie results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP1_treatment.stringtie.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Sun Aug 18 19:39:34 2024]
Error in rule stringtie:
    jobid: 35
    input: results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam, resources/annotation.gtf
    output: results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.transcripts.gtf, results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.gene.abundance.txt, results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.coverage.gtf, results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.ballgown
    log: logs/stringtie/RAP1_REP2_treatment.stringtie.log (check log file(s) for error details)
    conda-env: /home/lucianhu/rna_snakemake/test_ting/.snakemake/conda/c5aa9c6478b88eb8815e34b057a49de2_
    shell:
        
        stringtie results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam                   --rf                   -G resources/annotation.gtf                   -o results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.transcripts.gtf                   -A results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.gene.abundance.txt                   -C results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.coverage.gtf                   -b results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.ballgown                   -p 6                   -v                   -e &> logs/stringtie/RAP1_REP2_treatment.stringtie.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job stringtie since they might be corrupted:
results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.coverage.gtf, results/stringtie/RAP1_REP3_treatment/RAP1_REP3_treatment.ballgown
Removing output files of failed job stringtie since they might be corrupted:
results/stringtie/WT_REP1_control/WT_REP1_control.coverage.gtf, results/stringtie/WT_REP1_control/WT_REP1_control.ballgown
Removing output files of failed job stringtie since they might be corrupted:
results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.coverage.gtf, results/stringtie/RAP1_REP1_treatment/RAP1_REP1_treatment.ballgown
Removing output files of failed job stringtie since they might be corrupted:
results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.coverage.gtf, results/stringtie/RAP1_REP2_treatment/RAP1_REP2_treatment.ballgown
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-08-18T193934.852209.snakemake.log
unlocking
removing lock
removing lock
removed all locks
Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    dag_api.execute_workflow(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/api.py", line 594, in execute_workflow
    workflow.execute(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1286, in execute
    raise WorkflowError("At least one job did not complete successfully.")
snakemake_interface_common.exceptions.WorkflowError: At least one job did not complete successfully.

WorkflowError:
At least one job did not complete successfully.
